#!/usr/bin/env python3
"""Copy VibeCrew's bundled pipeline TOMLs into the plugin's override set.

The app bundle is now CANONICAL (`reference/routing.md` §7.1): every edit this
script used to apply — merge default-enabled, the `PLAN-FACTS:` line, the
`PLAN-GATE:` plan-size gate, the `CODER-MODEL:` step-up check, the merge
artifact gate, the never-commit-paperwork clauses — already lives in the
bundled files. So this script no longer transforms anything; it COPIES, stamps
the override banner, and ASSERTS that each canonical marker is still present.

Keeping it as a copier (rather than deleting it) preserves the two things it is
actually for: a one-command refresh of `pipelines/` after the app's TOMLs
change, and a tripwire that fails loudly if a canonical clause is dropped
upstream.

Usage:
  python3 generate_pipeline_overrides.py \
      --source ~/VibeCoding/vibecrew/CrewKit/Sources/CrewPipeline/Resources/DefaultPipelines \
      --out    <plugin>/pipelines
Deploy by copying the generated files to ~/.vibecrew/pipelines/ (user files
override bundled pipelines by `name =`).
"""

import argparse
import pathlib
import sys

# source filename -> output filename. Identity: the app's own TOMLs are already
# named `async-claude-*` / `async-opencode-*` / `async-pi-*` / `async-codex-*`,
# and the `name =` values are deliberately NOT touched — the app's registry
# shadows bundled pipelines by `name =`, so changing one would stop overriding
# the bundled pipeline and leave a stale duplicate in the picker.
ASYNC_FILES = {
    name: name
    for name in (
        "async-claude-sonnet.toml",
        "async-claude-opus.toml",
        "async-claude-fable.toml",
        "async-opencode-glm.toml",
        "async-opencode-glm-minimax.toml",
        "async-opencode-kimi-minimax.toml",
        "async-pi-glm.toml",
        "async-pi-glm-minimax.toml",
        "async-pi-kimi-minimax.toml",
        "async-codex-terra.toml",
        "async-codex-sol-terra.toml",
        "async-codex-sol.toml",
    )
}

HEADER = (
    "# Override of the bundled pipeline of the same name — generated by the vibecrew\n"
    "# plugin (sombrax_plugins) from the app's DefaultPipelines by\n"
    "# scripts/generate_pipeline_overrides.py. Do not hand-edit; regenerate.\n\n"
)

# Canonical clauses that MUST survive upstream. A miss means the app's bundled
# TOMLs lost something these overrides exist to carry — fail loudly rather than
# ship a silently weaker pipeline.
ASYNC_ASSERT_CONTAINS = [
    # The four-family coder rule, including Codex's own step-up rung.
    "on a Codex pipeline gpt-5.6-terra steps up to gpt-5.6-sol",
    "PLAN-FACTS:",
    "PLAN-GATE:",
    "CODER-MODEL:",
    "merge-record",
]

BASIC_ASSERT_CONTAINS = [
    "PLAN-FACTS:",
    "merge-record",
]


def assert_contains(text: str, needles, fname: str) -> str:
    for needle in needles:
        if needle not in text:
            sys.exit(
                f"{fname}: missing canonical clause {needle!r} — the app's bundled "
                "pipeline drifted; realign the generator (and the app) before shipping."
            )
    return text


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("--source", required=True, type=pathlib.Path)
    ap.add_argument("--out", required=True, type=pathlib.Path)
    ap.add_argument(
        "--header",
        choices=["plugin", "none"],
        default="plugin",
        help="'plugin' stamps the override banner (files that shadow the app's "
        "bundled set); 'none' writes bare files, for regenerating the app's OWN "
        "canonical DefaultPipelines in place.",
    )
    args = ap.parse_args()
    args.out.mkdir(parents=True, exist_ok=True)
    header = HEADER if args.header == "plugin" else ""

    outputs = dict(ASYNC_FILES)
    outputs["basic.toml"] = "basic.toml"
    for src_name, out_name in outputs.items():
        src = (args.source / src_name).read_text(encoding="utf-8")
        needles = BASIC_ASSERT_CONTAINS if src_name == "basic.toml" else ASYNC_ASSERT_CONTAINS
        (args.out / out_name).write_text(
            header + assert_contains(src, needles, src_name), encoding="utf-8")
        print(f"generated {out_name}  (from {src_name})")


if __name__ == "__main__":
    main()
